### PR TITLE
Fix ?large to also control size of dialog

### PR DESCRIPTION
**Pull request by laughinghan**
Passed along from `?large` to control the badge size, they now also
control the iframe and dialog size because after all, if you're on a
page with larger `font-size` that demands a larger badge, the small dialog
with small text is gonna look out of place:
screenshot of small dialog

The large badge is about 1.5x the size of the small badge (30px to 20px;
the other ratios aren't as exact), but I found that making the large
dialog 1.4x the size of the small dialog looked better than 1.5x
(that is, bumping the `em`/`rem` unit font size from 10px to 14px rather
than 15px), I think because at 1.5x the text in the dialog becomes bigger
than the text in the badge:

font-size: 14px
screenshot of 1.4x
vs
font-size: 15px
screenshot of 1.5x

--

See also https://github.com/rauchg/slackin/commit/6108430ed1698f4a0ea7d8bd966df3313582d667 for discussion of the `em`/`rem` technique

### CODE REVIEW

**Comment by rauchg** [comment]
Please rebase. I like this. I don't like the empty space at the bottom as much

**Comment by laughinghan** [comment]
@rauchg Done!

**Comment by rauchg** [comment]
@laughinghan is the empty space still there?

**Comment by laughinghan** [comment]
@rauchg
Nope, thanks to #153:
image

**Comment by rauchg** [comment]
Amazing. Thank you so much.

**Pull request merged**
