### PR TITLE
Implement reCAPTCHA for abuse prevention

### PR DESCRIPTION
**Pull request by chadwhitacre**
Redux of #234. Initial rebase here drops some README changes in favor of `HEAD`, but otherwise should match 8330ac6b6c873aaebf4e6692cef174a456040fe1.

### CODE REVIEW

**Comment by whit537** [comment]
Rebased again to drop the commits that add the `dist` directory to the repo: f5604a5671036c351322b0ba930c3bd636c97bf3 04d33c160ba38ece2f7cb665205f1305f4213b4b. That seems a distraction. Was 947d908cb6a601e69abe3a921f14a4269d122bd2.

**Comment by whit537** [comment]
Alright, squashed all the commits and removed the bits that were changing orthogonal plumbing vs. actually adding the feature in scope. Was c1294cc849c46992f6ce328cfebc64a5d5d2dfa4.

**Comment by whit537** [comment]
Testing with https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Frauchg%2Fslackin%2Ftree%2Fa7467a511a5dfa1849b28e13b7ff04f84d339b99 ...

**Comment by whit537** [comment]
screen shot 2017-05-26 at 9 08 14 pm

**Comment by whit537** [comment]
screen shot 2017-05-26 at 9 10 05 pm

**Comment by whit537** [comment]
screen shot 2017-05-26 at 9 10 25 pm

-------------------------

screen shot 2017-05-26 at 9 10 43 pm

**Comment by whit537** [comment]
Ready for review, @rauchg!

**Comment by whit537** [comment]
Test here if you like (will leave up temporarily):

https://immense-forest-91787.herokuapp.com/

**Comment by rauchg** [comment]
@whit537 thanks a lot! One last thing before we merge this: do you think it's a good idea to enforce Google reCAPTCHA on every single installation, rather than making it optional?

**Comment by whit537** [comment]
I think it should be hard to deploy SlackIn insecurely ("[secure by default](https://en.wikipedia.org/wiki/Secure_by_default)"). If reCAPTCHA is optional then it should be an explicit opt-out with a clear warning about [SlackOut](https://slackout.github.io/).

**Comment by whit537** [comment]
... and I guess I would see that as out-of-scope for this PR. Right now SlackIn exposes its users to a non-trivial vulnerability. Reducing that exposure is important. Adding a footgun back into SlackIn can be done later.

**Comment by whit537** [comment]
Ready to merge, @rauchg?

**Comment by whit537** [comment]
Announced: https://twitter.com/Gratipay/status/870366843000811521.

**Comment by toolmantim** [comment]
Was this made to also work with the badge version? Because I'm trying to upgrade (for Node security updates) but can't seem to get this to work, and I can't see how it did?

badge-version

When you try to send an invite you get:

> TypeError: undefined is not an object (evaluating 'gcaptcha_response.value')

It works fine if you go to it directly:

slackin

**Comment by whit537** [comment]
I don't recall seeing anything about the badge version when I was cleaning up the PR. I suggest making a new ticket/PR.

**Comment by toolmantim** [comment]
@whit537 I've done some digging, and it looks like you might have forgotten to update the badge to support recaptcha. I've opened up a WIP pull request here: https://github.com/rauchg/slackin/pull/332 Would love your help/thoughts.

**Comment by whit537** [comment]
> you might have forgotten to update the badge to support recaptcha

Sorry about that. :-/

**Comment by toolmantim** [comment]
It happens! 😊

**Comment by Daniel15** [comment]
Can you please publish this update to npm?

**Comment by jpoon** [comment]
FYI, this PR broke the Azure deployment: https://github.com/rauchg/slackin/issues/355. Need to update the environment variables here: https://github.com/rauchg/slackin/blob/master/azuredeploy.json#L99

**Comment by KrzysztofMadejski** [comment]
Azure deployment is fixed in https://github.com/rauchg/slackin/pull/333

**Pull request merged**
