### PR TITLE
Add success message for already signed up users

### PR DESCRIPTION
**Pull request by MaxWofford**
Would love to get a second set of eyes on this for review.

This adds onto #126, showing a new success message right before users get redirected to Slack.

### CODE REVIEW

**Comment by rauchg** [comment]
I think this is beautiful.

**Comment by rauchg** [comment]
What does the longer message look like in the button though? Maybe too much text?

**Comment by MaxWofford** [comment]
screenshot from 2016-01-25 20 21 54

Good point. I'll lowercase it and see how it looks.

**Comment by MaxWofford** [comment]
screenshot from 2016-01-25 20 36 02

Removing the uppercase helps, but removing the url looks much nicer.

screenshot from 2016-01-25 20 29 10

**Comment by rauchg** [comment]
Sending you to Slack is both concise and sufficient. Thank you!

**Pull request merged**
