### PR TITLE
support selection from list of channels

### PR DESCRIPTION
**Pull request by afeld**
Closes https://github.com/18F/slackin/issues/1.

At @18F, we have numerous projects in our team Slack that we want to start offering public chat rooms for. This PR allows multiple channel names to be specified, so the user can select from a list.

**Single (single-)channel**

screen shot 2015-05-04 at 2 29 34 am

**Multiple channels**

screen shot 2015-05-04 at 2 29 48 am

P.S. We plan to use slackin extensively – happy to help triage issues and go through PRs if you could use any maintainer help.

### CODE REVIEW

**Comment by afeld** [comment]
Live at https://chat.18f.gov/.

/cc @ultrasaurus @phirefly

**Comment by rauchg** [comment]
I like this! Super elegant.

**Comment by rauchg** [comment]
I think the single-channel scenario looks a bit ugly now though :\

**Comment by afeld** [comment]
Yeah, played around with a few different ways of handling it, but wasn't sure of the best option. Now will display the same way as before if there is only a single single-channel.

**Comment by rauchg** [comment]
<3

**Pull request merged**
