### PR TITLE
Remove the need for a build step

### PR DESCRIPTION
**Pull request by rstacruz**
Since you're using `require('6to5/register')` there should now be no need to have an extra build step to make `node/`.

### CODE REVIEW

**Comment by rauchg** [comment]
but how about requiring it as a module ? I would need an entry point file that loads 6to5 instead

**Comment by rauchg** [comment]
Also, to be completely honest, I think the build approach is better and faster than runtime + uncached build

**Comment by rauchg** [comment]
I actually pushed a fix to make `slackin(1)` startup faster just now :)

**Comment by rstacruz** [comment]
hmm—you're right, you do lose the ability to `require('slackin')`, but then again that's actually not supported right now (you don't have `index.js` or a `"main"` entry in package.json) ;)

**Comment by rauchg** [comment]
well, I should :) Thanks for mentioning that

**Comment by rauchg** [comment]
e68a5c2

**Pull request closed without merging**
