### PR TITLE
Use `<input type="email">`

### PR DESCRIPTION
**Pull request by d10**

### CODE REVIEW

**Comment by jomo** [comment]
:+1: *(although that means [not all valid email addresses](http://www.w3.org/TR/html5/forms.html#valid-e-mail-address) are accepted.)*

**Comment by rauchg** [comment]
This is advantageous for mobile web browsers correct?

**Comment by jomo** [comment]
yes. And browsers validate the field before submitting:
screenshot

**Comment by rauchg** [comment]
hot

**Pull request merged**
