### PR TITLE
Fix to run on Heroku

### PR DESCRIPTION
**Pull request by shimbaco**
I noticed that the error same as #221 and #229 has been occured in my slackin app. So I fixed it.

### CODE REVIEW

**Comment by ReanimationXP** [comment]
can this get merged please...

**Comment by rauchg** [comment]
@shimbaco @ReanimationXP let me know how it goes

**Comment by lfittl** [comment]
@rauchg Thanks this fixed it!

**Comment by shimbaco** [comment]
@rauchg Thank you for the merge! I already added this code to my slackin app and it seems to be working fine. :smiley:

**Comment by ReanimationXP** [comment]
worked like a charm, thanks.

**Pull request merged**
