### PR TITLE
Google recaptcha integration 

### PR DESCRIPTION
**Pull request by avatsaev**
Added Google recaptcha to discourage spammers from screwing with invite limits
Fixed deployment error on heroku (dist not found) by removed dist folder from gitignore

### CODE REVIEW

**Comment by jackmcdade** [comment]
Would love to see this merged.

**Comment by bmgdev** [comment]
+1

**Review by julianschiavo — APPROVED** [review]

**Comment by jackmcdade** [comment]
I've been using this fork for a few weeks now but it has recently just broken. The ReCaptcha's fail every time. I wouldn't merge this without resolving the issue.

**Comment by jaspergreenham** [comment]
Actually, I just installed it and noticed the same thing. How can it be fixed?

**Comment by jackmcdade** [comment]
@jaspergreenham If I knew i would fix it.

**Comment by jaspergreenham** [comment]
Did you make it?

**Comment by jackmcdade** [comment]
@jaspergreenham No, @avatsaev did.

**Comment by jaspergreenham** [comment]
Ah ok. @avatsaev, what’s happening?

**Comment by jaspergreenham** [comment]
I tweeted @avatsaev, let’s see if he replies.

**Comment by jaspergreenham** [comment]
Anyone here who knows a lot about Node.JS (I don't know much, just making a slack group for an event that's coming up) who can fix this?

**Comment by jackmcdade** [comment]
@jaspergreenham It's a bit late to expect much response on a fork of a niche app. I recommend a little patience :)

**Comment by jaspergreenham** [comment]
:)

**Comment by jaspergreenham** [comment]
YAY!!

I just found a nice one with Recaptcha:

https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fflexd%2Fslackinviter <https://dashboard.heroku.com/new?template=https://github.com/flexd/slackinviter>

Jasper

**Comment by jaspergreenham** [comment]
Everyone: It's easier to use this:

https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fflexd%2Fslackinviter 

Uses Go instead of node.js to use 10x less memory.

This one was not made by me, but I am using it (http://applenc.herokuapp.com) and think it's good.

**Comment by jackmcdade** [comment]
@jaspergreenham you're gonna recommend something else even after pinging @avatsaev in the middle of the night, and him fixing it within 8 hours? 

I for one, am very grateful. Thanks @avatsaev!!

**Comment by avatsaev** [comment]
you're welcome

**Comment by jaspergreenham** [comment]
I'm recommending it because it uses less memory and is generally faster and better.

I tweeted @avatsaev at 4pm my time, not knowing about the time difference. He immediately blocked me. This branch is slow and didn't work.

http://github.com/flexd/slackinviter is good. It works. It's fast.

That's why I'm promoting **the better** service

**Comment by jaspergreenham** [comment]
I've asked @rauchg to merge, he asked for link, I gave, now waiting to hear back :).

**Comment by rauchg** [comment]
Thanks @jaspergreenham. The PR is not mergeable. I also don't have any screenshots or anything else to ascertain what this looks like, therefore making it difficult to merge :|

**Comment by jackmcdade** [comment]
We're using it on slack.statamic.com. You can check it out there.

**Comment by passsy** [comment]
Thanks!

**Comment by rauchg** [comment]
@jackmcdade I'd like to only display it after pressing "get my invite". I'll adjust the PR myself

**Comment by lucymhdavies** [comment]
@rauchg any news on getting this PR updated and merged?

**Comment by whit537** [comment]
>  I also don't have any screenshots or anything else to ascertain what this looks like

-----------------------

screen shot 2017-05-25 at 4 59 06 pm

-----------------------

screen shot 2017-05-25 at 4 59 19 pm

-----------------------

screen shot 2017-05-25 at 4 58 49 pm

**Comment by whit537** [comment]
> The PR is not mergeable.

GitHub sez `unknown repo`. Is this PR orphaned? @avatsaev Can you make a new PR? Or update this one?

**Comment by rauchg** [comment]
@whit537 

It has merge conflicts:

```
.gitignore
README.md
bin/slackin
```

**Comment by whit537** [comment]
I recommend closing in favor of #311.

**Pull request closed without merging**
