### PR TITLE
Change invite with restricted to read from env.

### PR DESCRIPTION
**Pull request by xeodou**

### CODE REVIEW

**Comment by xeodou** [comment]
This will allow free user can send email. `restricted` is just a paid user option.

**Comment by rauchg** [comment]
I could reproduce the problem even with `channel` not present ?

**Comment by xeodou** [comment]
@rauchg If you create a new slack group without pay anything and use its web api token will get `{error=paid_only, ok=false}` this error. Without `restricted` property it will send the email out.

**Comment by xeodou** [comment]
This works for me last few days. And i have a test now , it doesn't work anymore.

**Pull request closed without merging**
