### PR TITLE
use shields.io directly for badge - fix #55

### LINKED ISSUE #55: Black ‘shield’ looks out-of-place
This looks pretty out-of-place:

screen shot 2015-05-06 at 6 24 40 pm

I'd also really like the option to customize the appearance of the badge, à la Shields:

    Slack chat-channel

Perhaps we could even get first-class treatment of Slackin' instances by @Badges / http://shields.io?

### PR DESCRIPTION
**Pull request by balupton**
this redirect means that the badge will always benefit from the latest shields.io rendering code, to be consistent with other badges, rather than whatever outdated version of the code we cache within our app

### CODE REVIEW

**Comment by balupton** [comment]
would be nice to also amend this so that the query-string is also forwarded over, enabling shields.io badge customisations

**Comment by rauchg** [comment]
@balupton definitely interested in improving that. Only concern is the extra network hoop? Maybe we should proxy instead?

**Comment by balupton** [comment]
I wouldn't consider the extra network loop to be of significance to performance.

**Comment by rauchg** [comment]
But right now we have design parity and better performance? It's hard to give up on that. Maybe shields has a module we can reuse to serve it ourselves?

**Comment by balupton** [comment]
Well, I wouldn't say design parity, this fixes #55 for instance.

**Comment by rauchg** [comment]
Fixed in `0.7.2`.

**Comment by espadrine** [comment]
@rauchg Hello, shields.io author / maintainer here.

I might be reading this wrong, but it feels like you are [not actually relying](https://github.com/rauchg/slackin/blob/master/lib/badge.js) on the [shields.io npm library](https://www.npmjs.com/package/gh-badges) (which, granted, is hard to find, thanks to complicated history). I would recommend using it in your case. See [this](https://github.com/badges/shields/blob/master/INSTALL.md#install-the-api) for example code.

SVG has gone a long way since we started the projects (and given the number of bugs we raised to various browsers, I hope we helped a bit in making it easier to author it), but there are still a few pitfalls and incompatibilities that we worked on avoiding.

As a side-note, my understanding of Microsoft's Core Fonts' license is that it is not really legal to publish a copy of the Verdana font on a GitHub project (or in any public URL) without their consent. As an aside, I would recommend to use the TTF available on macOS by default, instead of the one available on Windows or on Linux' ttf-mscorefonts-installer package.

Alternatively, you may want to redirect to the shields.io website, by using its `/badge/` endpoint, which would fix #73 for free.

Would you be interested by one of those choices? Would you consider a patch for it?

**Comment by devth** [comment]
Bump. I tried using `style=flat-squared` but it didn't seem to affect the style.

**Pull request closed without merging**
