### PR TITLE
Optional checkbox for code of conduct agreement

### PR DESCRIPTION
**Pull request by limulus**
Thanks for making and maintaining this project! In this PR I’ve implemented an option for a checkbox that ensures the user agrees to a linked code of conduct before requesting an invite. You can see it in action on the [TucsonJS slackin](http://chat.tucsonjs.org/). I suspect many other users of slackin may find this feature helpful.

Some notes on the implementation: Adding the option for the checkbox was relatively straightforward in the main interface, however it did add some complications with the badge dialog interface. The fact that the checkbox is optional causes the dialog to be of variable height, so I made the dialog adjust itself to the height of its content before showing itself (using the same methodology the badge uses to adjust its width).

Thanks for considering! Let me know if there is something I should have done differently.

### CODE REVIEW

**Comment by ndarville** [comment]
:+1:

**Comment by kizu** [comment]
:+1:

**Comment by cheeaun** [comment]
:+1:

**Comment by rauchg** [comment]
This is awesome! Thanks a lot. I have some concerns about the look n feel, will try to adjust it soon.

**Comment by megahbite** [comment]
I solved this a slightly different and perhaps simpler way in #98 but didn't check all the edge cases (I was focusing on the splash page). Perhaps the two PRs could be combined?

**Comment by megahbite** [comment]
For consistency's sake, would it not be better to handle the validation of the state of the checkbox in the same place as the email is validated: in the `/invite` handler in `index.js`?

**Comment by rauchg** [comment]
@megahbite agreed. If we were going to have one and not the other, I would have the `/invite` handler exclusively. Both sound good, provided that the client-side one provides the user feedback about the error.

**Pull request closed without merging**
