### PR TITLE
Use babel/register instead of babel/polyfill

### PR DESCRIPTION
**Pull request by elliottsj**
Using `'babel/register'` reduces some build complexity by no longer needing to use `make` to compile ES6 -> ES5.

### CODE REVIEW

**Comment by afeld** [comment]
Note that you can also

* Remove `node` from `.gitignore`
* Remove `RUN make` from the `Dockerfile`

See https://github.com/rauchg/slackin/pull/48.

**Comment by elliottsj** [comment]
@afeld Good call; I've just made a couple commits to remove those lines.

**Comment by rauchg** [comment]
We don't want to push the `node` transpiled build to github

**Comment by afeld** [comment]
Right – it will no longer need to get separately compiled. I could see the argument for keeping that path in in the `.gitignore` so that people who previously compiled don't accidentally commit it, but they should probably delete the directory anyway to avoid confusion. Does that make sense?

**Comment by rauchg** [comment]
Oh sorry missed the point of the PR. I think pre-compiling is a good idea performance wise. Otherwise you're transpiling unnecessarily every time you run the program.

**Comment by elliottsj** [comment]
I may be wrong about this, but I believe `babel/register` will [transform the source files and cache them](https://github.com/babel/babel/blob/1a716943bc95a4fecb69e98156cdd058968d8b49/src/babel/api/register/node.js#L64) only at build time; no run time performance drawbacks.

Even with the `make` build strategy, your machine will still need to spend time re-transpiling the source whenever you change a file and want to relaunch the server; I don't see a significant build performance difference.

**Comment by rauchg** [comment]
I'm not discussing a runtime slowdown. I'm discussing a execution slowdown. This makes running `slackin(1)` effectively slower. And in general, I like the idea of shipping code to NPM that's pre-compiled. Even if most servers will just build and run once and never restart the process.

**Pull request closed without merging**
